### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by vignesh0025-zz** [luciddreamz/laravel#1]
I can't see 'composer update' command anywhere in the action_hooks directory. Is composer supported?   I used laravel 4 with the following 'build' action hook. 
# !/bin/bash

export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"
if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
    curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR
else
    php $OPENSHIFT_DATA_DIR/composer.phar self-update
fi
( unset GIT_DIR ; cd $OPENSHIFT_REPO_DIR ; php $OPENSHIFT_DATA_DIR/composer.phar install )

https://github.com/vignesh0025/openshift-laravel4-quickstart/blob/master/.openshift/action_hooks/build

But i could'nt find a similar one here. So how does it support composer?

And please explain the settings of .env file configuration. If i want to add my data to remote .env file, how should i do it. I could'nt understand its working here. Its in .openshift directory for remote server. But how laravel will use it to get the required data.

**Comment by luciddreamz** [comment]
First off, regarding the .env file - I'm overwriting the `.env` file at the project root directory with the `.openshift/.env` file during the deploy process ([see line 76](https://github.com/luciddreamz/laravel/blob/master/.openshift/action_hooks/deploy#L76)).

Second off, the Laravel 4 QuickStart you're using is pretty old. It was created before OpenShift introduced native support for Composer. OpenShift announced support for Composer back in [June 2014](https://blog.openshift.com/more-online-features-june-2014/), however, it isn't well documented at the moment.

Composer support is built into the OpenShift PHP cartridge. All you have to do is set the ["use_composer" marker](http://docs.openshift.org/origin-m4/oo_cartridge_guide.html#php-markers), done [here](https://github.com/luciddreamz/laravel/blob/master/.openshift/markers/use_composer), and OpenShift does the following:

When in 'production' mode (default):

```
echo -n "Checking composer.json for Composer dependency... "
if [ -f ${OPENSHIFT_REPO_DIR}composer.json ]; then
    echo
    composer install --no-interaction --no-ansi --no-scripts --optimize-autoloader --working-dir=${OPENSHIFT_REPO_DIR} || \
    echo -e "\nSkipping Composer errors..\n\n  Please, fix the errors either locally or in development mode.\n"
    if [ ! -f ${OPENSHIFT_REPO_DIR}composer.lock ]; then
        echo -e $composer_lock_msg
    fi
else
    echo "File not found."
fi
```

When in 'development' mode:

```
if [ -f ${OPENSHIFT_REPO_DIR}composer.lock ]; then
    echo "Ignoring composer.lock file (development mode)"
fi
echo -n "Checking composer.json for Composer dependency... "
if [ -f ${OPENSHIFT_REPO_DIR}composer.json ]; then
    echo
    composer update --no-interaction --no-ansi --no-scripts --optimize-autoloader --working-dir=${OPENSHIFT_REPO_DIR}
    echo -e $composer_lock_msg
else
    echo "File not found."
fi
```

Check out the code beginning at [line #142 of the OpenShift PHP Cartridge](https://github.com/openshift/origin-server/blob/master/cartridges/openshift-origin-cartridge-php/bin/control#L142).

Check out the Developer Portal article I posted on [enabling development mode](https://developers.openshift.com/en/php-getting-started.html#development-mode) for more details.

**Comment by vignesh0025-zz** [comment]
Wow!! That's great. Thanks!

if i use <b>'rhc env set APPLICATION_ENV=development'</b>, will it affect environment settings of laravel? i.e in  <b>.env file, APP_ENV ? of remote server?</b>

**Comment by luciddreamz** [comment]
Yep - 'APP_ENV' will be set to match the value of 'APPLICATION_ENV' on the remote server. By default both values will be set to 'production'.

**Comment by luciddreamz** [comment]
I'll get back to you on that, while messing around this morning it looks like OpenShift's version of Composer is a bit outdated. I may end up having to revert to installing composer like the older Laravel 4 QuickStarts had been doing.

**Comment by luciddreamz** [comment]
Alright, I have a [pull request](https://github.com/openshift/origin-server/pull/6094/files) in with OpenShift Origin to update the `composer.phar` that comes bundled with the PHP cartridge. In the meantime, I've updated the readme and the [QuickStart on OpenShift Hub](https://hub.openshift.com/quickstarts/115-laravel-5-0) to make use of a [custom PHP cartridge](https://github.com/luciddreamz/openshift-php) with the update applied. I also updated the `pre_start_php` hook to set environment variables correctly on restart (see [here](https://github.com/luciddreamz/laravel/commit/32dbbf5e4fded806136f1a972f9a7fffc82ebf42)).

Moving on - 'APP_ENV' will be set to match the value of 'APPLICATION_ENV' on the remote server. By default, OpenShift's PHP cartridge assumes that no user-defined 'APPLICATION_ENV' variable equates to 'production'. In this case 'APP_ENV' will also be set to 'production'.

For reference, you can confirm that the values of `APP_ENV`, `APP_KEY`, `APP_URL`, and `DB_DRIVER` are set properly in production by running the `rhc env list` command.

For example, for an app named _laravelapp_ with a MySQL database:

```
$ rhc env list -a laravelapp
APP_ENV=production
APP_KEY=diEn9DIADEZQe2w7D24zUX7Tt0PwFQk
APP_URL=laravelapp-jlucky.rhcloud.com
DB_DRIVER=mysql
$ rhc env set APPLICATION_ENV=development -a laravelapp
Setting environment variable(s) ... done
$ rhc app restart -a laravelapp
RESULT:
laravelapp restarted
$ rhc env list -a laravelapp
APPLICATION_ENV=development
APP_ENV=development
APP_KEY=diLn9DIFBEZQe2w7D24zUZ7Tt0PwFQg
APP_URL=laravelapp-jlucky.rhcloud.com
DB_DRIVER=mysql
```
