### ISSUE TITLE
Cannot use Elixir (or other npm tasks) 

### ISSUE THREAD

**Issue by benVigie** [luciddreamz/laravel#10]
First of all, nice work ! It was really easy to deploy my Laravel app on Openshift with your cartridge, so thanks for that :smile: 

In order to fully automatize the deployment process, it would be cool to add a rule to execute `npm` tasks such as `gulp` or `bower`.

I added my npm tasks in the build hook, but I have the well knew rights error:

```
npm ERR! Error: EACCES, mkdir '/var/lib/openshift/XXXXXXX/.npm'
npm ERR!  { [Error: EACCES, mkdir '/var/lib/openshift/XXXXXXX/.npm']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/var/lib/openshift/XXXXXXX/.npm' }
npm ERR! Please try running this command again as root/Administrator.
```

I tried to figure out how I can enable `npm` on my gear, or change `npm`'s default temp folders but I didn't succeed so far.

There is a better and simpler way to do that directly in the Laravel Cartridge ?

**Comment by flashadvocate** [comment]
I guess the idea was to execute task runners locally, but this doesn't really work in cases where someone wants to develop solely via openshift

**Comment by benVigie** [comment]
It's not really helpful, as I need to build the app before using it.
I don't keep in my repo the builded website, I expect to build it once it's deployed.

So for the moment I just don't use openshift :/

**Comment by flashadvocate** [comment]
Same here. Ended up switching to Digital Ocean coupled with deploybot. Much more granular control than is available with openshift

**Comment by luciddreamz** [comment]
Again, bad news and good news. The bad - this would be very difficult on OpenShift v2. The good news, check out OpenShift v3 and granular customizations like this should be much easier if you know your way around Docker.
