### ISSUE TITLE
Openshift - New controller not found

### ISSUE THREAD

**Issue by wreeecks** [luciddreamz/laravel#11]
Hi,

I am new to openshift and i have a problem in deployment. I've pushed the updates to openshift repo by simply pushing to the master branch. It seems that the updates wasn't deployed properly. How do i make sure that all the updates are part of the deployment? I already added "php artisan cache:clear" on deploy action hook didn't help at all. 

How do check the last commit in the server? Thanks in advance.

**Comment by khaninejad** [comment]
Hi,

If you run your comment on the Openshift platform you need to pull back early created items likes Controllers.
to do that just login to your SSH and download created files, add them to your git and push it again.

That's all :)

**Comment by wreeecks** [comment]
Thanks @khaninejad ! I will try your suggestion.
