### ISSUE TITLE
Possible to turn off artisan serve?

### ISSUE THREAD

**Issue by christianesperar** [luciddreamz/laravel#15]
Not using this command is commonly use on shared hosting application but is this also possible to off on the cartridge. I just need this to one of my application.

**Comment by vignesh0025-zz** [comment]
It isn't even executed first of all... Why do you bother about that ?

**Comment by christianesperar** [comment]
Your right! I think I have problem when migrating our application from shared to cloud service. We have Laravel app on a Laravel app (2 Laravel application). I just seperate the 2 app.
