### ISSUE TITLE
composer self-update, composer.phar not be written

### ISSUE THREAD

**Issue by DiegoMPerez** [luciddreamz/laravel#18]
Today I try to use a "intervention/image": "^2.3.*", whe I use "composer update" I have this error ( Could not parse version constraint 4.x.x: Invalid version string "4.x.x"), I read about this and found it´s because the old composer version (1.0-dev  2015-03-09 23:06:06). The file composer.phar can be updated?

**Comment by christianesperar** [comment]
There is no composer.phar on this repo. Openshift do it for you since we put use_composer on the markers. If you mean the problem is happen locally then adding composer.phar will cause no harm :)

**Comment by Guerzizeb** [comment]
Hello, I have the same, it occur only when i make a "git push"! how can i solve this issue? in compose.json i used  "intervention/image": "^2.3".
Thanks.

**Comment by luciddreamz** [comment]
Well, the good news is that if you check out the Laravel 5.2 quickstart for OpenShift Online (Next Gen) Developer Preview you won't see this issue: https://github.com/luciddreamz/laravel-ex

Composer is now freshly installed each time your application builds: https://github.com/sclorg/s2i-php-container/blob/master/5.6/s2i/bin/assemble#L9-L26
