### ISSUE TITLE
Laravel 5.1 requires php5.6

### ISSUE THREAD

**Issue by impbob** [luciddreamz/laravel#6]
Hi,

Thank you for contributing this.

 I was wondering if you have any plans to upgrade to Laravel 5.1? It would also a PHP5.6 upgrade in the cartridge as well I think.

Thanks in advance.

**Comment by robert-cardillo** [comment]
Laravel 5.1 is LTS, so this would be awesome!

**Comment by ghost** [comment]
+1

**Comment by flashadvocate** [comment]
The author doesn't appear to be providing any support for this cartridge, so an update is probably not going to happen anytime soon

**Comment by luciddreamz** [comment]
I just finished up a Laravel 5.2 quickstart template for OpenShift Online (Next Gen / v3) Developer Preview: https://github.com/luciddreamz/laravel-ex

All future effort on the both the Laravel QuickStart and the OpenShift platform itself is heading this way.
